name: weather_buddy
description: Application made to get weather updates

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3 
  get: ^4.6.6
  dio: ^5.4.3+1
  sqflite: ^2.3.3+1
  geolocator: ^12.0.0
  jiffy: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/animations/